FROM rust:1.88-bookworm

ARG RUST_TARGET

ENV RUSTUP_DIST_SERVER=https://rsproxy.cn \
    RUSTUP_UPDATE_ROOT=https://rsproxy.cn/rustup

RUN sed -i \
        -e 's|http://deb.debian.org|https://repo.huaweicloud.com|g' \
        -e 's|http://security.debian.org/debian-security|https://repo.huaweicloud.com/debian-security|g' \
        /etc/apt/sources.list.d/debian.sources \
    && apt-get -o Acquire::Retries=5 update \
    && apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
        file \
        musl-tools \
        protobuf-compiler \
    && rustup target add "${RUST_TARGET}" \
    && rm -rf /var/lib/apt/lists/*
