FROM rust:1.88-bookworm

RUN apt-get -o Acquire::Retries=5 update \
    && apt-get -o Acquire::Retries=5 install -y --no-install-recommends file musl-tools pkg-config protobuf-compiler \
    && rustup target add aarch64-unknown-linux-musl \
    && rm -rf /var/lib/apt/lists/*
