ARG BASE_IMAGE=yr-base
FROM ${BASE_IMAGE}

COPY rrt-wheels/ /tmp/rrt-wheels/
RUN set -e; \
    set -- /tmp/rrt-wheels/openyuanrong_rrt*.whl; \
    test "$#" -eq 1 && test -f "$1"; \
    pip install --no-cache-dir "$1"; \
    rrt_runtime="$(python -c 'import openyuanrong_rrt; print(openyuanrong_rrt.runtime_path())')"; \
    test -x "${rrt_runtime}"; \
    ln -sf "${rrt_runtime}" /usr/local/bin/rrt-runtime; \
    rm -rf /tmp/rrt-wheels

WORKDIR /root
