# Patch files for external dependencies
package(default_visibility = ["//visibility:public"])

exports_files([
    "boringssl_shared.patch",
    "brpc_avoid_glog_flag_conflicts.patch",
    "brpc_fix_boringssl_compat.patch",
])
