{{- if and .Values.frontend.enabled (or (not (and .Values.dataPlane.enabled .Values.dataPlane.edge.enabled)) .Values.frontend.service.exposeWhenEdgeEnabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yr-k8s.componentName" (dict "root" . "component" "frontend") }}
  namespace: {{ include "yr-k8s.namespace" . }}
  labels:
    {{- include "yr-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- with .Values.frontend.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
{{- if not (and .Values.dataPlane.enabled .Values.dataPlane.edge.enabled) }}
    - name: router
      port: {{ .Values.frontend.service.routerPort }}
      targetPort: router
      protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
{{- end }}
