# Buildkite Test K8S overlay only. Do not use as the default deploy values file.
global:
  runtime:
    forceLowReliabilityInstance: true
frontend:
  enableEvent: true
  service:
    type: ClusterIP
    annotations: {}

dataPlane:
  enabled: true
  edge:
    enabled: true
    validateIam: false
    allowAnyClient: true
    tls:
      secretName: yr-edge-frontend-tls
  node:
    allowAnyEdge: true
  edgeNode:
    securityMode: network

traefik:
  enabled: false
